[
  /accounts/email.nix
  /files.nix
  /home-environment.nix
  /manual.nix
  /misc/dconf.nix
  /misc/debug.nix
  /misc/fontconfig.nix
  /misc/gtk.nix
  /misc/lib.nix
  /misc/news.nix
  # /misc/nixpkgs.nix
  /misc/numlock.nix
  /misc/pam.nix
  /misc/qt.nix
  /misc/submodule-support.nix
  /misc/tmpfiles.nix
  /misc/version.nix
  /misc/vte.nix
  /misc/xdg-mime.nix
  /misc/xdg-mime-apps.nix
  /misc/xdg-user-dirs.nix
  /misc/xdg.nix
  /programs/abook.nix
  /programs/afew.nix
  /programs/alacritty.nix
  /programs/alot.nix
  /programs/aria2.nix
  /programs/astroid.nix
  /programs/autojump.nix
  /programs/autorandr.nix
  /programs/bash.nix
  /programs/bat.nix
  /programs/beets.nix
  /programs/broot.nix
  /programs/browserpass.nix
  /programs/chromium.nix
  /programs/command-not-found/command-not-found.nix
  /programs/dircolors.nix
  /programs/direnv.nix
  /programs/eclipse.nix
  /programs/emacs.nix
  /programs/feh.nix
  /programs/firefox.nix
  /programs/fish.nix
  /programs/fzf.nix
  /programs/getmail.nix
  /programs/gh.nix
  /programs/git.nix
  /programs/gnome-terminal.nix
  /programs/go.nix
  /programs/gpg.nix
  /programs/home-manager.nix
  /programs/htop.nix
  /programs/i3status.nix
  /programs/info.nix
  /programs/irssi.nix
  /programs/lieer.nix
  /programs/jq.nix
  /programs/kakoune.nix
  /programs/keychain.nix
  /programs/kitty.nix
  /programs/lesspipe.nix
  /programs/lf.nix
  /programs/lsd.nix
  /programs/man.nix
  /programs/matplotlib.nix
  /programs/mbsync.nix
  /programs/mcfly.nix
  /programs/mercurial.nix
  /programs/mpv.nix
  /programs/msmtp.nix
  /programs/mu.nix
  /programs/ncmpcpp.nix
  /programs/ne.nix
  /programs/neomutt.nix
  /programs/neovim.nix
  /programs/newsboat.nix
  /programs/noti.nix
  /programs/notmuch.nix
  /programs/nushell.nix
  /programs/obs-studio.nix
  /programs/offlineimap.nix
  /programs/opam.nix
  /programs/password-store.nix
  /programs/pazi.nix
  /programs/pet.nix
  /programs/pidgin.nix
  /programs/powerline-go.nix
  /programs/qutebrowser.nix
  /programs/readline.nix
  /programs/rofi.nix
  /programs/rtorrent.nix
  /programs/skim.nix
  /programs/starship.nix
  /programs/ssh.nix
  /programs/taskwarrior.nix
  /programs/termite.nix
  /programs/texlive.nix
  /programs/tmux.nix
  /programs/urxvt.nix
  /programs/vim.nix
  /programs/vscode.nix
  /programs/vscode/haskell.nix
  /programs/waybar.nix
  /programs/z-lua.nix
  /programs/zathura.nix
  /programs/zoxide.nix
  /programs/zplug.nix
  /programs/zsh.nix
  /programs/zsh/prezto.nix
  /services/blueman-applet.nix
  /services/cbatticon.nix
  /services/clipmenu.nix
  /services/compton.nix
  /services/dropbox.nix
  /services/dunst.nix
  /services/dwm-status.nix
  /services/emacs.nix
  /services/flameshot.nix
  /services/fluidsynth.nix
  /services/redshift-gammastep/gammastep.nix
  /services/getmail.nix
  /services/gnome-keyring.nix
  /services/gpg-agent.nix
  /services/grobi.nix
  /services/hound.nix
  /services/imapnotify.nix
  /services/kanshi.nix
  /services/kbfs.nix
  /services/kdeconnect.nix
  /services/keepassx.nix
  /services/keybase.nix
  /services/keynav.nix
  /services/lieer.nix
  /services/lorri.nix
  /services/mako.nix
  /services/mbsync.nix
  /services/mpd.nix
  /services/mpdris2.nix
  /services/muchsync.nix
  /services/network-manager-applet.nix
  /services/nextcloud-client.nix
  /services/owncloud-client.nix
  /services/parcellite.nix
  /services/password-store-sync.nix
  /services/pasystray.nix
  /services/picom.nix
  /services/polybar.nix
  /services/pulseeffects.nix
  /services/random-background.nix
  /services/redshift-gammastep/redshift.nix
  /services/rsibreak.nix
  /services/screen-locker.nix
  /services/stalonetray.nix
  /services/status-notifier-watcher.nix
  /services/spotifyd.nix
  /services/sxhkd.nix
  /services/syncthing.nix
  /services/taffybar.nix
  /services/tahoe-lafs.nix
  /services/taskwarrior-sync.nix
  /services/udiskie.nix
  /services/unclutter.nix
  /services/unison.nix
  /services/window-managers/awesome.nix
  /services/window-managers/bspwm/default.nix
  /services/window-managers/i3-sway/i3.nix
  /services/window-managers/i3-sway/sway.nix
  /services/window-managers/xmonad.nix
  /services/xcape.nix
  /services/xembed-sni-proxy.nix
  /services/xscreensaver.nix
  /services/xsuspender.nix
  /systemd.nix
  # /targets/darwin.nix
  /targets/generic-linux.nix
  /xcursor.nix
  /xresources.nix
  /xsession.nix
]
